### ISSUE TITLE
Support Serialization using serde

### ISSUE THREAD

**Issue by generalelectrix** [petgraph/petgraph#139]
The backing collections behind Graph and friends are trivially compatible with serde if the node and edge weights implement Serialize and Deserialize.  As a client of this library, however, there's no way to do this, and instead one must resort to a complex/hacky scheme to do this.  Is there a simple way to provide this functionality without forcing all clients of this crate to take serde as a dependency?

Otherwise it seems that I'm left with forking this project and adding it myself, or implementing a hacky way to restore a serialized graph.

**Comment by Dushistov** [comment]
@generalelectrix You can just use http://stackoverflow.com/questions/42551113/is-it-possible-to-conditionally-derive-with-features and add suitable feature to `petgraph`, so it works for you and not touch users that not use `serde`.

**Comment by bluss** [comment]
Support for serde in some way would be great. Using their externalization feature sounds good, especially before they go 1.0.

I'm reminded of this feature (from elements); we have a basic way to build a graph from a basic representation of nodes and edges here https://docs.rs/petgraph/0.4.4/petgraph/data/trait.FromElements.html  but I don't think we have the opposite yet in a nice function — from graph into an elements iterator.

**Comment by generalelectrix** [comment]
Cool, it looks like it should be clean and easy to add serde support via a feature.  I'll try to get this working in my fork with forthcoming PR.

**Comment by fintelia** [comment]
Has there been any progress on this issue?

**Comment by generalelectrix** [comment]
I haven't dedicated any time to it as I've been focusing on other areas of the project that required it.  That project may also move away from using petgraph as it turns out a custom data structure may prove more suitable.

**Comment by bluss** [comment]
Let's get going. We need a good solution.

Proposed Design Criteria

- Graph and StableGraph have the same serialized representation. The stable distinction only matters while we are removing nodes and edges.
- No funky nodeindex etc wrapper types. Indices are integers

Ideas and Alternatives

- Support both "adjacency list" or "adjacency matrix" based representation
  - Counterargument: Graph/StableGraph are not good for dense graphs anyway
- Support eliding node/edge weights if weight types are `()`.

**Comment by bluss** [comment]
- Preserve graph indices across serialization
  - This one is important. Means that stable graph and graph are different.
- Preserve directionality across serialization (no weak typing / silent conversion)

**Comment by bluss** [comment]
I'm working on a proposal. Examples below.

Graph (Debug output)

```rust
```

Graph (JSON serialization)
```json
```

**Comment by bluss** [comment]
The question is if and how we can achieve that Graph and StableGraph share representation, and a StableGraph without holes is the same as a Graph.

**Comment by CraigHarley** [comment]
This looks like it's been implemented, but I'm having trouble getting it to work:

```
fn main() {
    let mut g = Graph::new();
    let a = g.add_node((0., 0.));
    let b = g.add_node((2., 0.));
    let c = g.add_node((1., 1.));
    let d = g.add_node((0., 2.));
    let e = g.add_node((3., 3.));
    let f = g.add_node((4., 2.));
    g.extend_with_edges(&[
        (a, b, 2),
        (a, d, 4),
        (b, c, 1),
        (b, f, 7),
        (c, e, 5),
        (e, f, 1),
        (d, e, 1),
    ]);

    let path = astar(&g, a, |finish| finish == f, |e| *e.weight(), |_| 0);
    serde_json::to_string(&Some((6, vec![a, d, e, f]))).unwrap();
}
```

This is the error message:
```
error[E0277]: the trait bound `petgraph::prelude::NodeIndex: serde::ser::Serialize` is not satisfied
  --> src\main.rs:33:5
   |
33 |     serde_json::to_string(&Some((6, vec![a, d, e, f]))).unwrap();
   |     ^^^^^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `petgraph::prelude::NodeIndex`
   |
   = note: required because of the requirements on the impl of `serde::ser::Serialize` for `std::vec::Vec<petgraph::prelude::NodeIndex>`
   = note: required because of the requirements on the impl of `serde::ser::Serialize` for `({integer}, std::vec::Vec<petgraph::prelude::NodeIndex>)`
   = note: required because of the requirements on the impl of `serde::ser::Serialize` for `std::option::Option<({integer}, std::vec::Vec<petgraph::prelude::NodeIndex>)>`
   = note: required by `serde_json::to_string`

error: aborting due to previous error
```

However it looks like the trait is implemented:
https://docs.rs/petgraph/0.4.10/src/petgraph/graph_impl/serialization.rs.html#74-78


I'm new to rust, am I missing something really simple?

**Comment by bluss** [comment]
hi @CraigHarley, yeah sounds like you need to enable the crate feature for this, "serde-1". See the top of the readme. It's correct that the most important types Graph, StableGraph now support serde serialization, while some other graphs don't yet.

**Comment by CraigHarley** [comment]
Thanks @bluss I will try that later this evening.

**Comment by saona-raimundo** [comment]
Hi there! Thanks for the serde support!

I noticed that `petgraph::Direction` does not implement serialization, even with `serde-1` feature.

As this issue is not closed yet, I wanted to do this tiny remark here.

**Comment by XVilka** [comment]
As this was mostly done, if something is still not serialized - please open a new issue, I am closing this one.
