### ISSUE TITLE
Support for multipartite or bipartite graph?

### ISSUE THREAD

**Issue by c410-f3r** [petgraph/petgraph#141]
Is it possible to simulate a multipartite or bipartite graph using the `UnionFind` struct ? If not, I could do some research and implement it in the library if you guys are willing to accept such feature.

**Comment by carrutstick** [comment]
Can you say anything more about what the benefits of this would be, or what additional functionality would be provided? Would this just give us a speedup on certain operations in the case that the graph is multipartite?

**Comment by leoyvens** [comment]
I came looking for an algorithm to find a minimum vertex cover on a bipartite graph and found this issue. The Hopcroft–Karp algorithm runs only on bipartite graphs.
