### ISSUE TITLE
Custom Metadata for Nodes and Edges

### ISSUE THREAD

**Issue by candronikos** [petgraph/petgraph#240]
Is there a way to add meta data for Nodes and Edges?

What I'm trying to do is annotate an edge to specify the respective port it's connected to of each node but there are plenty of other reasons why you'd want to do this.

Would be nicer, in my opinion, than maintaining a data structure outside of this and have to look it up every time.

**Comment by jmcomets** [comment]
I don't understand what you mean by "metadata".

Nodes & Edges have *weights*, which, depending on the graph implementation you use, can be considered as custom user data. `GraphMap` for example, uses node weights as node IDs, whereas `Graph` doesn't require anything from the node weights. 

My point is that you could wrap your current node weight in a struct, adding a "metadata" field.

**Comment by bluss** [comment]
metadata seems to just be a different name for the *weights* indeed. Feel free to reopen if this is not enough.
