### ISSUE TITLE
A way to pick a random node for Graph

### ISSUE THREAD

**Issue by Stargateur** [petgraph/petgraph#244]
### Summary
To pick a random node, I currently do:

```rust
NodeIndex::new(rng.gen_range(0, graph.node_count()));
```

### Motivation

Need to pick a random node for implement a maze generation.

### Details

I don't think this cause problem for Graph cause it's guarantee that index are between 0 and `graph.node_count()` according to the doc. I don't know if this could be better with a trait.

I'm willing to implement this myself, I think something like `pub fn node_rand<T>(&self, &mut rng: Rng) -> Option<NodeIndex<Ix>>`

**Comment by jmcomets** [comment]
I don't think this issue should be addressed directly by petgraph. Currently, `rand` is a dev dependency, only used for unionfind & quickcheck tests. Moreover, I believe this use-case is too niche to justify another trait (we already have a bunch of those).

I suggest two alternative solutions to yours, which work for all graph implementations:
1) Keep the node IDs when you add nodes, maybe store them in a `Vec` & pick from there. This costs memory but you get nice `O(1)` access to node IDs.
2) Use the `g.node_indices()` iterator, and use `nth(i % g.node_count())` with `i` being some random index. This uses practically no memory but is `O(|N|)` time complexity.

**Comment by bluss** [comment]
Closing, since we want to avoid adding rand as a public dependency at this time.
