### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ignatenkobrain** [petgraph/petgraph#246]
It would be awesome if you would release new version with updated dependencies...

**Comment by XVilka** [comment]
It makes sense to support [quickcheck>0.8.0](https://github.com/bluss/petgraph/issues/253) in it, and [migrate to Rust 2018](https://github.com/bluss/petgraph/pull/254). Ah, and fix [the failing `dot` test](https://github.com/bluss/petgraph/issues/255).

**Comment by waywardmonkeys** [comment]
Failing `dot` test is fixed on `master` now (PR #260).

**Comment by waywardmonkeys** [comment]
I'm going to start tracking the issues for this under a "Release 0.5" milestone.

**Comment by Marwes** [comment]
A new release would be great, its been over a year since the last one and fixes like https://github.com/petgraph/petgraph/pull/215 are not in.

**Comment by birkenfeld** [comment]
Just another ping here - I used git master for Advent of Code last year, and still couldn't update to a release ;)

**Comment by XVilka** [comment]
Thanks to everyone involved - 0.5.0 release is ready: https://github.com/petgraph/petgraph/releases/tag/0.5.0

**Comment by XVilka** [comment]
@bluss could you please publish it on crates.io? I have no permissions there.

**Comment by XVilka** [comment]
cc @waywardmonkeys @jrraymond @jmcomets

**Comment by bluss** [comment]
Thanks xvilka!, my usual dev env is not running, so I can't push the release right now, but can eventually. Would be cool if others could publish

**Comment by jrraymond** [comment]
Merry Christmas everyone ;)  https://crates.io/crates/petgraph/0.5.0
