### ISSUE TITLE
Add method to lookup target nodes for source node and edge and the other way around

### ISSUE THREAD

**Issue by iddan** [petgraph/petgraph#264]
### Summary

`pub fn get_targets(&self, source: NodeIndex<Ix>, edge: EdgeIndex<Ix>) -> Iterator<Item=NodeIndex<Ix>>`
For given source node and edge returns target node.

`pub fn get_sources(&self, edge: EdgeIndex<Ix>, target: NodeIndex<Ix>) -> Iterator<Item=NodeIndex<Ix>>`
For given edge and target node returns source node.

### Motivation

Efficiently lookup connected nodes.

### Details

* What code needs to change? New traits? Which modules?  Should extend the Graph trait with two new methods.

* Are you willing to implement this yourself? Mentor someone else and help them
  implement it? I am willing to implement myself with mentorship.

**Comment by bluss** [comment]
Graph::edge_endpoints already lets you look up the *source* and *target* for any given edge on Graph or StableGraph
