### ISSUE TITLE
Listing incoming nodes for digraphmap

### ISSUE THREAD

**Issue by serpilliere** [petgraph/petgraph#281]
### Test Case
```rust
use ::petgraph::{ graphmap::DiGraphMap, Direction};

fn main() {
    let mut graph: DiGraphMap<u32, u32> = DiGraphMap::new();

    let n0 = graph.add_node(0);
    let n1 = graph.add_node(1);
    let n2 = graph.add_node(2);

    /*
    Graph:
    0 -> 1
    1 -> 1
    1 -> 2
     */

    for (x, y) in [
        (n0, n1),
        (n1, n1),
        (n1, n2),
    ].iter() {
        graph.add_edge(*x, *y, 0);
    }

    println!("Graph edges:");
    for (src, dst, _) in graph.all_edges() {
        println!("{} -> {}", src, dst);
    }

    println!("Outgoing nodes:");
    for node in graph.nodes() {
        println!("Node: {:?}", node);
        for predecessor in graph.neighbors_directed(node, Direction::Outgoing) {
            println!("\toutgoing: {:?}", predecessor);
        }
    }

    println!("Incoming nodes:");
    for node in graph.nodes() {
        println!("Node: {:?}", node);
        for predecessor in graph.neighbors_directed(node, Direction::Incoming) {
            println!("\tincoming: {:?}", predecessor);
        }
    }
}

```

### Steps To Reproduce
Compile and run the example :smiley:

### Actual Results
```
Graph edges:
0 -> 1
1 -> 1
1 -> 2
Outgoing nodes:
Node: 0
        outgoing: 1
Node: 1
        outgoing: 1
        outgoing: 2
Node: 2
Incoming nodes:
Node: 0
Node: 1
        incoming: 0
Node: 2
        incoming: 1
```

### Expected Results
```
Graph edges:
0 -> 1
1 -> 1
1 -> 2
Outgoing nodes:
Node: 0
        outgoing: 1
Node: 1
        outgoing: 1
        outgoing: 2
Node: 2
Incoming nodes:
Node: 0
Node: 1
        incoming: 0
        incoming: 1
Node: 2
        incoming: 1
```

### Summary

For me there is a bug here: The "incoming" result should be symetric to the "outgoing" result. 

### Motivation

So if a node self loops, as the "outgoing" result displays the node self looping, the api should definitlely return the self looping node in the "incoming" result as well.

### Details

In the present case the calling parent is:
```rust
    pub fn neighbors_directed(&self, a: N, dir: Direction)
        -> NeighborsDirected<N, Ty>
    {
        NeighborsDirected {
            iter: match self.nodes.get(&a) {
                Some(neigh) => {
                    neigh.iter()
                },
                None => [].iter(),
            },
            dir: dir,
            ty: self.ty,
        }
    }
```
This code seems ok as if we look at the `neigh.iter()` for node 1, we have 3 neighbors (0, 1, 2).

If I understand correctly the code, in "src/graphmap.rs", the bug seems to be in:
```rust
            (&mut self.iter)
                .filter_map(move |&(n, dir)| if dir == self_dir {
                    Some(n)
                } else { None })
                .next()
```

The direction information for node 1 seems to be stored as an "outgoing" link between 1 and 1.
So when the iterators test the direction, it skips node 1 so we have the current result.

My first idea was to fix NeighborsDirected to add a test of the self node, but the iterator doesn't seem to have access to the original node :cry:

**Comment by jmcomets** [comment]
I had a look at the implementation of `add_edge()` and found this comment: https://github.com/petgraph/petgraph/blob/98fb3ff6c5ae60912db87aec283c7703ed8357ce/src/graphmap.rs#L247-L252

I'm not quite sure what was the reasoning behind this, but IMO this is a bug. I'll try digging a bit in the repo's history to find out more.

Here's the smallest test needed to reproduce the bug:
```rust
#[test]
fn neighbors_incoming_includes_self_loops() {
    let mut graph = DiGraphMap::new();

    let node = graph.add_node(());
    graph.add_edge(node, node, ());

    assert_eq!(graph.neighbors_directed(node, Incoming).next(), Some(node));
}
```

**Comment by serpilliere** [comment]
Thank you @jmcomets  and @bluss !
