### ISSUE TITLE
Induced subgraph

### ISSUE THREAD

**Issue by bonsairobo** [petgraph/petgraph#283]
### Summary

I would like to get the induced subgraph of some `Graph` given a `Set<NodeIndex>`.

### Motivation

Useful for filtering down large graphs.

### Details

Just needs a new method on the `Graph` type.

**Comment by bonsairobo** [comment]
Here's a quick implementation that's probably not quite good enough, but it's basically what I want:

```
pub fn induced_subgraph<N: Clone, E: Clone, Ty: EdgeType>(
    graph: &Graph<N, E, Ty>, nodes: &HashSet<NodeIndex>
) -> Graph<N, E, Ty> {
    let mut subgraph = Graph::default();

    let mut new_node_ids = HashMap::new();
    for n in nodes.iter() {
        new_node_ids.insert(n, subgraph.add_node(graph[*n].clone()));
    }
    for e in graph.edge_indices() {
        if let Some((n1, n2)) = graph.edge_endpoints(e) {
            if nodes.contains(&n1) || nodes.contains(&n2) {
                subgraph.add_edge(new_node_ids[&n1], new_node_ids[&n2], graph[e].clone());
            }
        }
    }

    subgraph
}
```

**Comment by bonsairobo** [comment]
In particular, I'm trying to use this with the set of node indices returned from the connected components algorithms.

**Comment by bluss** [comment]
Stable/Graph::filter_map can already do this, can't they?

**Comment by bonsairobo** [comment]
Oh I must have missed that. Thanks!
