### ISSUE TITLE
RLS unable to compile Petgraph

### ISSUE THREAD

**Issue by kellytk** [petgraph/petgraph#284]
https://github.com/rust-lang/rls/issues/1560

**Comment by bluss** [comment]
Thanks for the info. Any clue about what in the crate causes this? Since a wide range of Rustc compiles it, I assume our code is well formed.

**Comment by kellytk** [comment]
I've created a [minimal example](https://github.com/kellytk/x-rls) demonstrating the problem.

The development environment is:

* macOS 10.14.5
* VS Code 1.35
* RLS 0.6.1
* rustc 1.40.0-nightly (032a53a06 2019-10-03)
* cargo 1.40.0-nightly (8b0561d68 2019-09-30)

If I can be of further assistance don't hesitate to ask.

**Comment by benesch** [comment]
Seems to be a rustc bug: https://github.com/rust-lang/rust/issues/64659

**Comment by kellytk** [comment]
Thank you @benesch.
