### ISSUE TITLE
StableGraph::from_elements(min_spanning_tree(&graph)) asserts that node does not exist in graph

### ISSUE THREAD

**Issue by bonsairobo** [petgraph/petgraph#288]
### Test Case

Here's the JSON-serialized representation of the `Undirected` `StableGraph` I'm using: https://gist.github.com/bonsairobo/1897e608f031cf076ca09df12f5665c3

### Steps To Reproduce

Load the graph and call `StableGraph::from_elements(min_spanning_tree(&graph))`.

### Actual Results

Here's the stack trace:

```
thread '<unnamed>' panicked at 'StableGraph::add_edge: node index 978 is not a node in the graph', .cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.4.13/src/graph_impl/stable_graph/mod.rs:400:17
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   3: std::panicking::continue_panic_fmt
   4: std::thread::local::fast::Key<T>::try_initialize
   5: petgraph::graph_impl::stable_graph::StableGraph<N,E,Ty,Ix>::add_edge
   6: <petgraph::graph_impl::stable_graph::StableGraph<N,E,Ty,Ix> as petgraph::data::Build>::add_edge
             at .cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.4.13/src/data.rs:166
   7: petgraph::data::from_elements_indexable
             at .cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.4.13/src/data.rs:295
   8: <petgraph::graph_impl::stable_graph::StableGraph<N,E,Ty,Ix> as petgraph::data::FromElements>::from_elements
             at .cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.4.13/src/data.rs:323
```

### Expected Results

A valid graph is created from the MST.

**Comment by bonsairobo** [comment]
Even simpler graph with the same problem:

JSON:
```
{"nodes":[17,25,26,27,30,48,56,69,73,82,85,91,96],"node_holes":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,49,50,51,52,53,54,55,57,58,59,60,61,62,63,64,65,66,67,68,70,71,72,74,75,76,77,78,79,80,81,83,84,86,87,88,89,90,92,93,94,95],"edge_property":"undirected","edges":[null,null,null,null,null,null,null,null,null,null,null,null,null,[17,25,null],[17,82,null],[17,91,null],null,null,null,null,null,[25,82,null],[26,56,null],[26,69,null],[27,96,null],null,null,[30,48,null],[30,56,null],null,null,null,null,null,null,[48,73,null],null,null,null,[56,85,null],null,null,[69,96,null],null,[73,82,null]]}
```

Dot:
```
graph {
    17 [label="17"]
    25 [label="25"]
    26 [label="26"]
    27 [label="27"]
    30 [label="30"]
    48 [label="48"]
    56 [label="56"]
    69 [label="69"]
    73 [label="73"]
    82 [label="82"]
    85 [label="85"]
    91 [label="91"]
    96 [label="96"]
    17 -- 25
    17 -- 82
    17 -- 91
    25 -- 82
    26 -- 56
    26 -- 69
    27 -- 96
    30 -- 48
    30 -- 56
    48 -- 73
    56 -- 85
    69 -- 96
    73 -- 82
}
```

This time it's "node index 25 is not a node in the graph."

But it seems clear from both representation that node 25 is in the graph.

**Comment by bluss** [comment]
ok, looks like a bug. as a workaround until it's solved please create a Graph from the iter, then convert to StableGraph.

**Comment by bonsairobo** [comment]
I don't think I can use that workaround, because I need to get the maintain the node indices of the graph after finding the MST. I want to be able to index the original graph with the same indices that I find in the MST.

Thankfully I have a different workaround in mind that is specific to my use case (because I have unique node weights).

**Comment by bluss** [comment]
It's weird that we have this oversight, but more analysis during fixing will answer if it's possible and a good design to keep the node indices through these APIs. From the design of FromElements, I don't think so.

**Comment by carrutstick** [comment]
So to me it looks like the problem is that `Node` `Element`s don't carry an index, and so are assumed to be indexed by the order in which they're added to a graph, whereas the `MinSpanningTree` iterator uses the graph's actual node indices when constructing `Edge`s. The two ways to fix this would be:

1. make sure that any time a `StableGraph` is converted into `Element`s, the edges in the `Element`s use a relabelling of the nodes consistent with the order the node `Element`s are produced, or
2. modify the `Node` `Element` to carry an index, and add support for specifying a node's index when it is added to a `StableGraph`.

Option 2 would obviously be far more invasive.

I think the decision comes down to whether we want to have first-class support for persistent node indices... that is, do we think of a node index as a label for that node, or is it just an implementation detail that is supposed to be abstracted away. If the latter, then what is our story for how a user can maintain a reference to a particular node after doing transformations (such as `min_spanning_tree`) to their graph?

**Comment by XVilka** [comment]
Can you please send a PR? I think this the only bug worth fixing before crafting a 0.5.0 release: https://github.com/petgraph/petgraph/milestone/1

**Comment by carrutstick** [comment]
I was kinda hoping to get more feedback from people who are more actively involved in the library about which solution was preferred. After thinking about it a while, I don't know what the point of computing a minimum spanning tree would be if you couldn't identify the indexes in the result with the indexes in the original graph, so I'm leaning towards the more-invasive solution 2. I'll take a closer look this week.
