### ISSUE TITLE
Get subgraph and export to .dot

### ISSUE THREAD

**Issue by idahogray** [petgraph/petgraph#321]
I have tried to read the API documentation and searched online but I can't figure out how to get a subgraph that I can export to a .dot file. 

I have created a large graph with multiple root nodes. I want to export one .dot file for each root node and its subgraph.

Any tips or pointers would be appreciated. Please let me know if I can provide more information.

**Comment by kper** [comment]
What do you mean with getting a subgraph?
Is a Breadth-First-Search an option for you (https://docs.rs/petgraph/0.5.0/petgraph/visit/struct.Bfs.html)?

Export: https://docs.rs/petgraph/0.5.0/petgraph/dot/struct.Dot.html

**Comment by idahogray** [comment]
By subgraph I mean that I want to create a new graph, based on the existing graph, that is a subset of the original nodes and edges. I will try to draw out my example here, hopefully this helps. In my specific case, I have a graph with multiple root nodes (n1, n4, n7).

```
n1--e1---->n2
  \---e2--->n3
n4--e3---->n5
  \---e4--->n6
n7--e5---->n8
  \---e6--->n9
```

I can already export the entire graph to a dot file. What I want to do is create 3 dot files, one for each subgraph created by only taking the parts of the graph connected to each root node.

I hope that illustration helps, please let me know if it still isn't clear. 

Also, I think there is a function, though I couldn't find it again in the docs, that will take a graph as well as two closures, and give you a new graph. The first closure filters out the nodes and the second filters the edges. I couldn't figure out how to do what I wanted with it, but it may be the answer.

**Comment by kper** [comment]
@idahogray is that what you need?
```
use petgraph::dot::{Config, Dot};
use petgraph::prelude::*;
use petgraph::visit::Dfs;

use std::io::Write;

fn main() {
    let mut og = Graph::new_undirected();
    let n1 = og.add_node(1);
    let n2 = og.add_node(2);
    let n3 = og.add_node(3);
    let n4 = og.add_node(4);
    let n5 = og.add_node(5);
    let n6 = og.add_node(6);
    let n7 = og.add_node(7);
    let n8 = og.add_node(8);
    let n9 = og.add_node(9);

    og.add_edge(n1, n2, 0);
    og.add_edge(n1, n3, 0);

    og.add_edge(n4, n5, 0);
    og.add_edge(n4, n6, 0);

    og.add_edge(n7, n8, 0);
    og.add_edge(n7, n9, 0);

    let subgraph1 = get_subgraph(&og, n4);

    let mut fs = std::fs::File::create("test.dot").unwrap();
    fs.write_all(format!("{}", Dot::with_config(&subgraph1, &[Config::EdgeNoLabel])).as_bytes())
        .unwrap();
}

type MyGraph = Graph<usize, usize, petgraph::Undirected>;

fn get_subgraph(graph: &MyGraph, root: NodeIndex) -> MyGraph {
    let mut subgraph = Graph::new_undirected();

    let mut dfs = Dfs::new(&graph, root);
    let mut nodes = std::collections::HashMap::new();
    let mut discovered = std::collections::HashSet::new();

    while let Some(node) = dfs.next(&graph) {
        let mut neighbors = graph.neighbors_undirected(node).detach();

        while let Some(edge) = neighbors.next_edge(&graph) {
            if !discovered.contains(&edge) {
                // neighbors_undirected will walk the graph twice because it is undirected
                discovered.insert(edge);

                let (g_from, g_to) = graph.edge_endpoints(edge).unwrap();

                if !nodes.contains_key(&g_from.index()) {
                    let n = subgraph.add_node(*&graph[g_from]);
                    nodes.insert(g_from.index(), n);
                }

                if !nodes.contains_key(&g_to.index()) {
                    let n = subgraph.add_node(*&graph[g_to]);
                    nodes.insert(g_to.index(), n);
                }

                let s_from = nodes.get(&g_from.index()).unwrap();
                let s_to = nodes.get(&g_to.index()).unwrap();

                subgraph.add_edge(*s_from, *s_to, 0);
            }
        }
    }

    subgraph
}
```

**Comment by XVilka** [comment]
@idahogray was your question answered? Can I close this issue?

**Comment by idahogray** [comment]
Sorry, I haven't had a chance to get back to this. I will close it.
