### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by korken89** [petgraph/petgraph#324]
Hi all,

Are there any plans for no_std support?
I'd love to have the power of this library in an environment without allocation (micro-controllers).

Thanks!

**Comment by jmcomets** [comment]
#238 mentions just this. I think it just needs a little rebase effort before it's ready to merge.

**Comment by korken89** [comment]
Thanks for pointing me in the right direction!

**Comment by mitchmindtree** [comment]
Hi @korken89! Did you ever get #238 rebased and working locally? If so, any chance you'd be up for opening a PR for it?

**Comment by TheButlah** [comment]
Hi, I would also like to request no_std support, if possible :)

I'm happy to PR a feature for it.
