### ISSUE TITLE
Why are graphmap nodes required to implement Copy?

### ISSUE THREAD

**Issue by mankinskin** [petgraph/petgraph#325]
I would like to have a graph with Strings as node weights, but unfortunately it is not possible to implement `Copy` for any type containing a `String`, which is required for `graphmap::NodeTrait`. Is `Clone` not enough for Node weights?

**Comment by jmcomets** [comment]
Hi there!

Quoting the [docs](https://docs.rs/petgraph/0.5.0/petgraph/graphmap/struct.GraphMap.html):

> The node weight N must implement Copy and will be used as node identifier, duplicated into several places in the data structure.

The key detail here is that it will be duplicated into *several* places, and as such is kept as `Copy` to prevent suboptimal usage. If it was only `Clone` was required, graphmap would unnecessarily copy your strings when you should probably be using an external storage for node data.

Anticipating the debate on whether graphs' should contain additional data or simply focus on structure, petgraph follows the latter idiom. In the past, I've had success with the following pattern:

```rust
struct NodeIndex {
    max_node_id: usize,
    node_ids: HashMap<Node, usize>, // replace `Node` with your type / generify
}

impl NodeIndex {
    pub fn new() -> Self {
        NodeIndex {
            max_node_id: 0,
            nodes: HashMap::new(),
        }
    }

    pub fn index(&mut self, node: Node) -> usize {
        let ref mut max_node_id = self.max_node_id;

        let node_id = *self.node_ids.entry(node)
            .or_insert_with(|| {
                let node_id = *max_node_id;
                *max_node_id += 1;
                node_id
            });

        node_id
    }
}
```

**Comment by mankinskin** [comment]
Thank you for the explanation. But why is the node weight used as the node identifier? Isn't that potentially inefficient? And what if you want to have multiple nodes with the same weight? It seems simpler and more efficient to do what your code does all of the time. Just map node weights to node indices, which are used internally to refer to nodes. This would allow the Graph structure to store the more types as weights directly.
Also I found the NodeIndex structure in this library a little confusing, maybe this is because nodes are internally identified with their weights instead of with an internal index.

**Comment by timthelion** [comment]
@mankinskin If you don't want to use the inefficient GraphMap implementation than don't. There is more than one implementation for that very reason. You might find my article https://thobbs.cz/rust-play/petgraph-internals.html on the various implementations helpful in choosing the one which is right for your usecase.
