### ISSUE TITLE
Canonicolizing petgraph

### ISSUE THREAD

**Issue by mankinskin** [petgraph/petgraph#327]
I find that there are many variants of the same patterns in petgraph, so I would like to start a list of things which should maybe be canonicolized:

- refactor `NodeReference`, `NodeId`, `NodeIndex`
- provide same interface through `EdgeReference` or `EdgeIndex`
- rename `Graph::raw_nodes()` to `get_nodes()` or `node_iter()`

**Comment by timthelion** [comment]
`raw_nodes()` is a lower level version of `node_references` which is a method of the trait [`IntoNodeReferences`](https://docs.rs/petgraph/0.5.0/petgraph/graph/struct.Graph.html#impl-IntoNodeReferences). It's not a duplicate concept, but rather a method specific to `Graph`.

I agree that `NodeId` and `NodeIndex` seem to be duplicates. But [`NodeRef`](https://github.com/petgraph/petgraph/blob/712b5482e368814264461bc635eccd0759822626/src/graph_impl/mod.rs#L2039) (`NodeReference` doesn't exist) is much more powerful and has slightly higher overhead.

**Comment by jmcomets** [comment]
Adding to the discussion about refactoring traits/structs, there's always the issue of modularizing the crate. @bluss has spoken a few times about splitting the crate into different components:
- traits
- algorithms
- impls

The current petgraph crate could be rewritten to depend on the previous three for backwards compatibility. `petgraph-algo` would likely depend on `petgraph-traits` as well.

Then there's always the issue of the various utilities which are used: `UnionFind` is a good example, but I think there's a few we may discover when doing this.

I'm not trying to hijack the discussion on traits here, but if I were to refactor a bunch of existing petgraph traits in a breaking change, I'd probably change the crate's structure as well. 2c
