### ISSUE TITLE
Finding a cycle in a graph

### ISSUE THREAD

**Issue by lpil** [petgraph/petgraph#329]
In [my application](https://github.com/gleam-lang/gleam) I'm building a graph and then using `toposort` to put them in an order before traversing them. When there is a cycle I wish to be able to disable a friendly error message to the user so that they can correct the cycle, so I wish to show them which nodes are the problem.

Is there a recommended way to determine which nodes in the graph make a cycle?

Thank you!

**Comment by kper** [comment]
Hello!
First, I guess you mean "display" and not "disable".

Second, you already said that you are using `toposort` which returns a result ` Result<Vec<G::NodeId>, Cycle<G::NodeId>>`. So is it not exactly what you want? :) 

https://docs.rs/petgraph/0.5.0/petgraph/algo/fn.toposort.html

**Comment by lpil** [comment]
> First, I guess you mean "display" and not "disable".

Thanks! fat thumbs :)

> Second, you already said that you are using toposort which returns a result Result<Vec<G::NodeId>, Cycle<G::NodeId>>. So is it not exactly what you want? :)

I was looking for all the nodes in the cycle and was wondering if there was a built in for this, but i guess not! I'll implement it myself. Thanks ! :)

**Comment by bluss** [comment]
The scc algorithms can do this, each scc is a cycle or a single node. Picture: https://www.geeksforgeeks.org/strongly-connected-components/
