### ISSUE TITLE
Create Gitter community

### ISSUE THREAD

**Issue by XVilka** [petgraph/petgraph#342]
To discuss the related things that are out of the scope of the GitHub issues.
I suggest creating https://gitter.im/petgraph (I can't since not in the control of this organization).

https://gitter.im/#createcommunity

**Comment by bluss** [comment]
Xvilka, thanks for working on petgraph 0.5.0 and taking care of petgraph. I'll add you to the organization. Do you want to manage future releases too? Please speak openly about what you expect from me or other maintainers too, I unfortunately don't have enough time to spend on petgraph, and my interest is firmely in fundamentals / data structures, not algorithms, when I don't have the time.

I would suggest, if it helps, to have stints of fixes (minor releases, 0.5.1,.2,.3 etc) and then bunch up breaking changes when it has calmed down, and ideally trying to keep the time that code is merged but not released (on crates.io) as short as possible.

The gitter question should be decided by active maintainers, so not me :) As long as Rust is focusing on discord, I'd consider it as a possible alternative, for example the rust community discord.

**Comment by akiross** [comment]
If I can chime in for just one suggestion: zulip and matrix are also being used by some rust communities; gitter has been acquired by element (the company behind matrix), so adopting gitter could be a good choice in the long run. Also, these tools are open source and have some kind of integration - that seems to be a bit problematic with discord.

**Comment by XVilka** [comment]
I created Gitter then - https://gitter.im/petgraph-rs/community

Sorry for the inactivity lately, I will return back to the petgraph starting next month.
