### ISSUE TITLE
Incorrect documentation for `GraphMap::edges`

### ISSUE THREAD

**Issue by Coder-256** [petgraph/petgraph#364]
### Test Case

```rust
use petgraph::graphmap::UnGraphMap;

fn main() {
    let mut graph = UnGraphMap::<usize, ()>::new();
    graph.add_edge(1, 2, ());
    graph.add_edge(1, 3, ());
    
    for (_, n, ()) in graph.edges(1) {
        println!("Neighbor: {}", n);
    }
}
```

As expected, this prints:

```
Neighbor: 2
Neighbor: 3
```

The issue is the `_` in the `for` loop binding. [The documentation states](https://docs.rs/petgraph/0.5.1/petgraph/graphmap/struct.GraphMap.html#method.edges):

> Iterator element type is `(N, &E)`.

However, it is actually `(N, N, &E)`: the node passed to `edges()`, followed by the other node of the edge, and then the edge weight. The documentation should be fixed to reflect this, but maybe `(N, &E)` is actually a more sensible return for the next breaking version?

**Comment by insideoutclub** [comment]
My pull request that addresses this issue has been committed. What's the process for resolving the issue?
