### ISSUE TITLE
GraphBLAS integration

### ISSUE THREAD

**Issue by fabianmurariu** [petgraph/petgraph#365]
Are you interested in integrating with GraphBLAS?

Not sure if you're aware of the initiative to redefine operations on graphs as linear algebra operations on sparse matrices over various semirings.

The initial candidate for this would be a directed unweighted graph. This is easily represented as a sparse boolean matrix.

I maintain https://github.com/fabianmurariu/rustgraphblas would you consider a PR for this?

**Comment by SuperFluffy** [comment]
There has been some effort getting suitesparse integrated with [sprs](https://github.com/vbarrielle/sprs). Specifically, you have a rust implementation of cholesky factorization which is inspired by suitesparse, here: https://github.com/vbarrielle/sprs/master/sprs-ldl.

Are you aware of their efforts? Maybe you can join forces?

**Comment by fabianmurariu** [comment]
I guess what I'm asking would you take a PR for a graph implementation on top of GraphBLAS if I wrote one?

**Comment by XVilka** [comment]
Depends on what inside this PR, but in general - yes, of course we would be happy to.

**Comment by fabianmurariu** [comment]
After looking at the code and the work involved, I decided against it for now.
