### ISSUE TITLE
Unable to reproduce sample code

### ISSUE THREAD

**Issue by slyons** [petgraph/petgraph#385]
### Test Case

Taken from `simple_paths.rs`, using the same imports.

```rust
let graph = DiGraph::<i32, i32, _>::from_edges(&[
            (0, 1),
            (0, 2),
            (0, 3),
            (1, 2),
            (1, 3),
            (2, 3),
            (2, 4),
            (3, 2),
            (3, 4),
            (4, 2),
            (4, 5),
            (5, 2),
            (5, 3),
        ]);
```

### Steps To Reproduce

* Copy
* Paste

### Actual Results

```rust
the trait `IndexType` is not implemented for `i32`
```

### Expected Results

Compilation.

Overall as someone coming in to this library with fresh eyes I've found the documentation a bit sparse when it comes to some basic examples, you really have to root around for them.

**Comment by bluss** [comment]
Rust uses whole-function type inference. The place you have copied this from has further code that informs type inference as to which index type to use. Your code (you haven't shown exactly all of it) is missing that. Suggestion is to change to use `DiGraph::<i32, i32>::from_edges` and it will compile (notice change in type parameters).
