### ISSUE TITLE
Iterator over StableGraph node weights with shared borrow

### ISSUE THREAD

**Issue by bollian** [petgraph/petgraph#388]
### Summary

I would like to be able to obtain an iterator over all the node weights of a `StableGraph` with shared, rather than exclusive, access. This doesn't need to return in any particular order. Essentially, I want `StableGraph::node_weights_mut` without the `_mut`.

### Motivation

Currently I'm imitating this functionality with code along the lines of `graph.node_indices().map(|i|&graph[i])`. However, this is clearly not the prettiest or most convenient code ever. It should also be easy to implement, being nearly identical to `node_weights_mut`.

### Details

* Implementation should be nearly identical to `node_weights_mut`
* For feature parity, this should probably also be implemented for the normal `Graph` type
* I'm willing to do this work myself

**Comment by ABorgna** [comment]
Hi. This was added in #423, so it will be in the next release :)
