### ISSUE TITLE
is_isomorphic_subgraph fails on certain graphs

### ISSUE THREAD

**Issue by jessberg** [petgraph/petgraph#401]
### Test Case

```
use petgraph::graph::Graph;
use petgraph::algo::is_isomorphic_subgraph;

fn isomorphism_check() {
    let mut graph0 = Graph::<&str, &str>::new();
    let a = graph0.add_node("a");
    let b = graph0.add_node("b");
    let c = graph0.add_node("c");
    let e1 = graph0.add_edge(a, b, "");
    let e1 = graph0.add_edge(b, c, "");

    let mut graph1 = Graph::<&str, &str>::new();
    let x = graph1.add_node("x");
    let y = graph1.add_node("y");
    let z = graph1.add_node("z");
    let w = graph1.add_node("w");
    let e2 = graph1.add_edge(x,y,"");
    let e2 = graph1.add_edge(y,z,"");
    let e2 = graph1.add_edge(x,w,"");

    assert!(is_isomorphic_subgraph(&graph0, &graph1));
}
```
### Steps To Reproduce

* This bug only happens with the version of petgraph obtained by cloning the github repository.  It looks like subgraph isomorphism is a new feature that has not been released yet but has been merged into the repository.  However, when it was merged, only one test case was given.  It fails on other simple graphs.
* Once that version is used, the test above fails.

### Actual Results

The code above will fail on the assert, despite the fact that the graphs are subgraph isomorphic.  Graph0 is just a string of three nodes, and graph1 is a string of 3 nodes with an extra node added to the root.

### Expected Results

One would expect that the assert would not fail.

**Comment by dajose** [comment]
@ABorgna any chance you could check @cojuer the fix proposal? it works for me
