### ISSUE TITLE
Inconsistencies in scc algorithms

### ISSUE THREAD

**Issue by code-ape** [petgraph/petgraph#409]
> **Overview**
>
> I was writing some trivial tests for comparing `tarjan_scc` and `kosaraju_scc` when I stumbled across ~two~ **one** unusual thing:
>
> 1. ~The sccs (`Vec<Vec<NodeIndex>>`) have a single entry for each non-strongly connected node (in this example nodes `4`, `5`, and `6`) but they are not self referencing nodes.~ **This is proper behavior, see comments below.**
> 2. Both algorithm documents state *"The order of node ids within each scc is arbitrary, but the order of the sccs is their postorder (reverse topological sort)"* and yet they are not returning SCCS in the same order.
>
> This is not a critical issue for me, but I wanted to file something in case this was a more significant problem for others.
>
> Cheers! @code-ape

### Test Case

![petgraph_issue_visual_1](https://user-images.githubusercontent.com/3579192/112760910-aa656380-8fc6-11eb-8677-4c2d330d1f2f.png)
*Test data visualization*

```rust
#[test]
fn tarjan_scc_matches_kosaraju_scc() {
    let (g, _nodes, _edges) = new_test_graph3();
    let t_scc_groups = algo::tarjan_scc(&g);
    let k_scc_groups = algo::kosaraju_scc(&g);

    assert_eq!(t_scc_groups, k_scc_groups);
}

pub fn new_test_graph3() -> (DiGraph<(), ()>, Vec<NodeIndex>, Vec<EdgeIndex>) {
    let mut g = DiGraph::new();
    // Create 7 nodes
    let nodes = vec![g.add_node(()),g.add_node(()),g.add_node(()),g.add_node(()),g.add_node(()),g.add_node(()),g.add_node(())];
    // Create 10 edges
    let edges = vec![
        g.add_edge(nodes[1], nodes[0], ()),
        g.add_edge(nodes[1], nodes[3], ()),
        g.add_edge(nodes[1], nodes[2], ()),
        g.add_edge(nodes[0], nodes[3], ()),
        g.add_edge(nodes[0], nodes[2], ()),
        g.add_edge(nodes[3], nodes[2], ()),
        g.add_edge(nodes[4], nodes[1], ()),
        g.add_edge(nodes[4], nodes[0], ()),
        g.add_edge(nodes[4], nodes[3], ()),
        g.add_edge(nodes[5], nodes[6], ()),
    ];
    (g, nodes, edges)
}
```

### Steps To Reproduce

Run the test on Rust 1.51.0.

### Actual Results

```
running 1 test
thread 'algo::tests::tarjan_scc_matches_kosaraju_scc' panicked at 'assertion failed: `(left == right)`
  left: `[[NodeIndex(3), NodeIndex(1), NodeIndex(2), NodeIndex(0)], [NodeIndex(4)], [NodeIndex(6)], [NodeIndex(5)]]`,
 right: `[[NodeIndex(6)], [NodeIndex(5)], [NodeIndex(0), NodeIndex(3), NodeIndex(2), NodeIndex(1)], [NodeIndex(4)]]`', src/algo/mod.rs:104:9
```

### Expected Results

Test should either pass or fail due to scc component order different, not from difference in order of scc groups.

**Comment by bluss** [comment]
https://en.wikipedia.org/wiki/Strongly_connected_component says SCC creates a partition into subgraphs, and if singlet components were removed, it wouldn't be a partition anymore. So I don't think including the singlets is a bug, but the ordering issue you mention may well be.

**Comment by code-ape** [comment]
> ... says SCC creates a partition into subgraphs, and if singlet components were removed, it wouldn't be a partition anymore ...

Ah! Apologies. New to using scc algorithms and wasn't aware. I'll update the issue to only be about the ordering.

Also, friendly offer, happy to open a documentation PR to add a bit of verbiage and an example for singlet's being included in scc output. If it's something you'd like :)

**Comment by saolof** [comment]
Kosaraju's algorithm inherently does not topologically sort the components, unlike Tarjan's algorithm which does topologically sort at the same time.

**Comment by ABorgna** [comment]
Both results in the test are valid (reversed) topological sorts. There is no canonical choice between orders, so I'd say this is correct behaviour.
