### ISSUE TITLE
Struct `petgraph::graph::Externals` does not implement Clone

### ISSUE THREAD

**Issue by TheZalli** [petgraph/petgraph#416]
### Summary

The iterator struct `Externals` seems to have missed some trait implementations that it could have, most critically Clone.

### Motivation

Some cases, like the `cycle`-iterator adapter requires, require the iterator to be Clone which would make using the `Externals` struct a bit easier if it had that trait.
Also adding the Debug trait might be good too.

### Details

I don't see any problems from just adding an auto-derive for it, since the internal `iter::Enumerate` already has Clone (and Debug) too.
It also has some other traits implemented, such as `DoubleEndedIterator`, `ExactSizeIterator` etc, but I'm not sure if implementing those is necessary or compatible with the future API.

I will try to make a fork and a pull request for the change at some point unless someone wants to do it before me.

**Comment by bluss** [comment]
See this call https://github.com/petgraph/petgraph/pull/415#issuecomment-823391361 :)
