### ISSUE TITLE
Suggestion: Create a petgraph Discord

### ISSUE THREAD

**Issue by TheZalli** [petgraph/petgraph#419]
At the moment the communication between the developers and maintainers of this crate to me seems a bit haphazard and uncoordinated,
I think it would warrant to create a Discord server or something similar where we could discuss about things such as what areas we should develop or how to and where to contribute.

If people here are familiar with other chatrooms then we could use that as well, but I'm most familiar with Discord and I believe many other people will be as well. It would also be a great way for the users of this crate to ask for questions on how to use this crate and such.

**Comment by bluss** [comment]
Previous discussion https://github.com/petgraph/petgraph/issues/342  it's on matrix #petgraph-rs_community:gitter.im  and I've now joined since it's on matrix (not keen on gitter but matrix should be fine).

**Comment by TheZalli** [comment]
Ok I'll try to use that then. A discord might be a bit more accessible for users though, which is something to consider.

**Comment by ABorgna** [comment]
I'm ok with both. 
It would be nice to add a gitter badge to the readme if we keep that.

**Comment by ABorgna** [comment]
Closing this. Changing to discord can be an option on the future, but let's stay with gitter for now.
