### ISSUE TITLE
Bump MSRV for release 0.6

### ISSUE THREAD

**Issue by ABorgna** [petgraph/petgraph#428]
Since we are planning on doing a major release, we can update the Minimum Supported Rust Version (current one is 1.37).

- The last version of `fixedbitset` requires 1.39.
- #424 discusses using the `non_exaustive` attribute, which requires 1.40.

Should we go for 1.40? Anyone proposes something more recent?

**Comment by mtreinish** [comment]
If possible could we avoid going above 1.41 (so 1.40 works quite well for me)? 1.41 is the version of rustc that debian buster is currently shipping and at least for some of my downstream user base it's very important to be able to compile the library I maintain that's built on petgraph with the debian version of rustc.

**Comment by ABorgna** [comment]
Another datapoint:

- The no_std (#370) will add [`hashbrown`](https://github.com/rust-lang/hashbrown) as a dependency, which has a MSRV of **1.49**. hashbrown0.9.1 (from 2020-09-28) still supported 1.36, so we'd have to use that version if we keep to something lower.

**Comment by ABorgna** [comment]
- Looks like IndexMap may require 1.49 soon since it also depends on hashbrown https://github.com/bluss/indexmap/pull/181.

**Comment by mtreinish** [comment]
Unless you actually require the latest version (for api compatibility reasons, new features, or something else) you can just set a version range, something like: https://github.com/PyO3/pyo3/blob/main/Cargo.toml#L30. That way downstream crates that use it can use the version that meets their constraints. I actually use hashbrown in my crate (for the rayon iterator support) but have it fixed at 0.9 for rustc 1.41 support.

**Comment by ABorgna** [comment]
I set the new version to 1.41 :)
We'll deal with the new indexmap and hashbrown versions when we need them.
