### ISSUE TITLE
Removing a node in a directed GraphMap does not remove incoming edges

### ISSUE THREAD

**Issue by wabain** [petgraph/petgraph#431]
When using a directed GraphMap, removing a node does not remove incoming edges to that node. I believe this is a bug—as far as I can tell, the expected invariant is that a node only has an entry in its adjacency list if the neighbor is in the graph and also has the corresponding adjacency. The documentation for remove_node mentions that it removes edges in `O(|V|)`.

This reproduces on master as well as 0.5.1.

### Test Case

```rust
use petgraph; // 0.5.1

fn main() {
    let mut graph = petgraph::graphmap::DiGraphMap::<u32, ()>::new();
    
    graph.add_edge(1, 2, ());
    graph.remove_node(2);
    
    let neighbors: Vec<u32> = graph.neighbors(1).collect();

    assert_eq!(neighbors, []);
}
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=970bb94ee486e410950f857b6a133619))

### Actual Results

```rust
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[2]`,
 right: `[]`', src/main.rs:11:5
```

### Expected Results

I would expect `2` to be no longer be yielded as a neighbor of `1` once the node `2` has been removed from the graph.

I also hit this when using `petgraph::dot::Dot`, where it manifested as a panic on `Option::unwrap` in the impl of `petgraph::visit::NodeIndexable::to_index`. Backtrace snippet:

```
   3: core::option::Option<T>::unwrap
             at $path/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: <petgraph::graphmap::GraphMap<N,E,Ty> as petgraph::visit::NodeIndexable>::to_index
             at $path/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.5.1/src/graphmap.rs:933:25
   5: <&G as petgraph::visit::NodeIndexable>::to_index
             at $path/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.5.1/src/visit/macros.rs:129:21
   6: petgraph::dot::Dot<G>::graph_fmt
             at $path/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.5.1/src/dot.rs:159:17
   7: <petgraph::dot::Dot<G> as core::fmt::Debug>::fmt
             at $path/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.5.1/src/dot.rs:198:9
```

**Comment by ABorgna** [comment]
Thanks, I'll look into this.
