### ISSUE TITLE
Keep the indices valid when removing node and edge

### ISSUE THREAD

**Issue by liangjs** [petgraph/petgraph#456]
### Summary

When we remove a node or an edge from the graph, the last node/edge index becomes invalid. In some cases (see Motivation), this can make the graph library hard to use.

I understand that, the current implementation of removal behaves like swap_remove so that the Graph's nodes/edges vector can be compact and fast. However, I think there is a better way to handle node/edge removal (see Details).

### Motivation

For example, I want to remove all the nodes that have no incoming edges to them, and keep removing nodes until no such node can be found.

A simple and fast implementation is to use a queue to store nodes (indices) to be removed. In each iteration, we pop a node, remove it from the graph, and add neighbors with no incoming edges to the queue.
However, when a node is removed from the graph, some node indices in the queue become invalid.

### Details

We can mark whether the node/edge index is still valid, for example, by changing the internal structure of Graph `nodes: Vec<Node<N, Ix>>` to `nodes: Vec<Option<Node<N, Ix>>>`. When a node is going to be removed, we set the corresponding position to `None`, so it does not affect other node indices.

But when a lot of removals are processed in this way, the nodes/edges vector will become sparse. To solve this, we can add a new API (refine_index?) that rearranges the indices and makes previous indices invalid. So the user can choose a proper time to clean up.

I don't think I can implement this, but I would like to help.

**Comment by ABorgna** [comment]
Hi. You may be interested in [`StableGraph`](https://docs.rs/petgraph/0.6.0/petgraph/stable_graph/struct.StableGraph.html), which does not modify the vertices ids on removals.

Internally it does something similar to what you mention, wrapping a Graph's nodes with Options and keeping a free-id list :)
