### ISSUE TITLE
[Question / Feature Request] How to check whether node is present in the graph by label?

### ISSUE THREAD

**Issue by tomekozlowski** [petgraph/petgraph#507]
Can't find any way to access labels thus I am unable to find a workaround. When adding nodes by label, same name labels get duplicated. 

The only thing I can think of is pre-indexing what's necessary outside of the crate but since there are similar methods in here just not for node labels but edges for example it would be amazing to have it.

**Comment by Swiddis** [comment]
I'm also struggling with this, though since the issue is closed it looks like a solution was found. Better documentation for would be nice, at least.

**Comment by tomekozlowski** [comment]
It is in the documentation but as part of an example for something different. Manually iter: `g.node_indices().find(|i| g[*i] == label)` this returns Option<>

**Comment by Swiddis** [comment]
That makes sense. I also found `GraphMap` which is designed for the operation and can be used instead.
