### ISSUE TITLE
Specify order of topological walk

### ISSUE THREAD

**Issue by cloudhead** [petgraph/petgraph#526]
### Summary

It would be very useful to be able to specify the order in which to traverse neighbors in a topological walk.

### Motivation

We're using petgraph to encode an operation based CRDT (each graph node is an operation) as a DAG, and one of the important things to ensure is that the final state is not influenced by the order of concurrent operations. In this case a concurrent operation would mean two potential graph traversal orders, as there's no direct edge between the two concurrent ops. This is essential a "partial order" of operations.

### Details

To be able to test this, we'd want some kind of control over how neighbors are iterated over I guess, when there's more than one possible sort order. Say we have a graph like this:
```
             ┌────────b◄─────┐
             ▼               │
             a               d
             ▲               │
             └────────c◄─────┘
```
There are two possible topological traverse orders: `[a, b, c, d]` and `[a, c, b, d]`. Having a way to go through these different orders would be super handy.

One option would be to allow random order traversal. This would allow us to test all orders by running the test enough times to likely test all permutations.

I'm happy to try implementing this if you think it makes sense.

Thanks!

**Comment by mkpankov** [comment]
I've stumbled upon similar problem while working on a toy spreadsheet processor (Advent of Code 2022 - day 21). My graph is a binary tree and I always want to visit nodes like this: 
```
left operand
right operand
expression
```

**Comment by cloudhead** [comment]
Found this test, which shows that the traversal is in LIFO order of the edges:
```rust
#[test]
fn neighbor_order() {
    let mut gr = Graph::new();
    let a = gr.add_node("a");
    let b = gr.add_node("b");
    let c = gr.add_node("c");
    gr.add_edge(a, b, 0);
    gr.add_edge(a, a, 1);

    gr.add_edge(c, a, 2);

    gr.add_edge(a, c, 3);

    gr.add_edge(c, a, 4);
    gr.add_edge(b, a, 5);

    // neighbors (edges) are in lifo order, if it's a directed graph
    assert_eq!(gr.neighbors(a).collect::<Vec<_>>(), vec![c, a, b]);
    assert_eq!(
        gr.neighbors_directed(a, Incoming).collect::<Vec<_>>(),
        vec![b, c, c, a]
    );
}
```

**Comment by cloudhead** [comment]
I ended up implementing a DAG from scratch which supports arbitrary order traversal, so won't be needing this anymore. If you still need this, happy to re-open it, just let me know.

**Comment by oovm** [comment]
I encountered a similar problem, the LIFO order was not what I wanted and I couldn't control the declaration order of edges.

I want to know how you traversal in arbitrary order.

I hope that nodes at the same level can be sorted according to a certain key.

---

I'm trying to figure out the wasm module instantiation order issue, there are dependencies between types, so modules have to be instantiated in a certain order.

In some cases the order given is:

```js
Module(wasi:io/error@0.2.0)
Resource(wasi:io/error@0.2.0, error)
Module(wasi:io/streams@0.2.0)
Resource(wasi:io/streams@0.2.0, output-stream)
Variant(stream-error)
Module(wasi:io/get@0.2.0)
External(wasi:io/get@0.2.0, std∷io∷standard_output)
External(wasi:io/streams@0.2.0, std∷io∷OutputStream∷blocking_write_and_flush)
External(wasi:io/streams@0.2.0, std∷io∷OutputStream∷write_and_flush)
```

This conforms to the definition of topological sort, but is illegal because `wasi:io/streams` cannot be instantiated twice.

I expect to do secondary sorting using module as key.
​
A legal order of instantiation is:

```js
Module(wasi:io/error@0.2.0)
Resource(wasi:io/error@0.2.0, error)
Module(wasi:io/streams@0.2.0)
Resource(wasi:io/streams@0.2.0, output-stream)
Variant(stream-error)
External(wasi:io/streams@0.2.0, std∷io∷OutputStream∷blocking_write_and_flush)
External(wasi:io/streams@0.2.0, std∷io∷OutputStream∷write_and_flush)
Module(wasi:io/get@0.2.0)
External(wasi:io/get@0.2.0, std∷io∷standard_output)
```
