### ISSUE TITLE
Implement an edges_connecting(a, b) iterator for Graph

### ISSUE THREAD

**Issue by mitchmindtree** [petgraph/petgraph#53]
Was just thinking about this when addressing your [comment](https://github.com/mitchmindtree/daggy/pull/8#discussion-diff-49275422R495) - I realised it's probably not unusual for two nodes to be joined by multiple edges (perhaps of different variants). It is quite common in conrod [for example](https://github.com/PistonDevelopers/conrod/blob/master/src/graph/mod.rs#L118).

**Comment by bluss** [comment]
New method to do this would be appropriate.

**Comment by bluss** [comment]
Old title: Should `find_edge(a, b)` be `find_edges(a, b)` producing an Iterator or Walker instead of an Option?

**Comment by jmcomets** [comment]
I don't know if I understood this correctly, but I gave it a try [here](https://github.com/jmcomets/petgraph/commit/745d0720d8bc436ba5abe42ac5a986e7e1eb0189).

Since I can't figure out how to refer to a commit, here's the gist of it:
```rust
pub fn edges_connecting(&self, a: NodeIndex<Ix>, b: NodeIndex<Ix>) -> HashSet<NodeIndex<Ix>> {
    // Get all of a's successors
    let predecessor_map = {
        let mut open_set = vec![a];
        let mut closed_set = HashSet::new();
        let mut predecessor_map = HashMap::new();

        while let Some(node) = open_set.pop() {
            // don't go past b
            if node == b {
                continue
            }

            for neighbor in self.neighbors(node) {
                predecessor_map.entry(neighbor)
                    .or_insert(vec![])
                    .push(node);

                let inserted = closed_set.insert(neighbor);
                if inserted {
                    open_set.push(neighbor);
                }
            }
        }

        predecessor_map
    };

    // Get all nodes in b's predecessors
    let mut open_set = vec![b];
    let mut closed_set = HashSet::new();
    while let Some(node) = open_set.pop() {
        if let Some(ref neighbors) = predecessor_map.get(&node) {
            for neighbor in neighbors.iter().cloned() {
                if neighbor == a {
                    continue
                }

                let inserted = closed_set.insert(neighbor);
                if inserted {
                    open_set.push(neighbor);
                }
            }
        }
    }

    closed_set
}
```

Obviously it's gonna need some rework for correctness / performance, but does the general idea match what we're trying to get here?

**Comment by sdleffler** [comment]
Hi, I'd really like to have this feature. What would be necessary to implement it? I'm willing to buckle down and do it if it won't take long.

**Comment by sdleffler** [comment]
I suppose that since `find_edge` is `O(e')` in the first place, it would make sense to simply use `neighbors` in the underlying implementation. We could do this very simply as an iterator filtering neighbors of `a` for edges targeting the `b` node.
