### ISSUE TITLE
The trait bounds in `extend_with_edges` (`From<Dummy>` is not implemented for `NodeIndex`)

### ISSUE THREAD

**Issue by m-spitfire** [petgraph/petgraph#530]
### Test Case

```rust
use petgraph::graph::Graph;
use petgraph::dot::{Dot, Config};

#[derive(Copy, Clone, Debug, Default)]
struct Dummy(usize);

fn main() {
    let d1 = Dummy(1);
    let d2 = Dummy(2);
    let d3 = Dummy(3);
    let d4 = Dummy(4);
    let mut graph = Graph::<Dummy, ()>::new();

    graph.extend_with_edges(&[(d3, d1), (d3, d2), (d1, d4)]);

    println!("{:?}", Dot::with_config(&graph, &[Config::EdgeNoLabel]));
}
```

### Steps To Reproduce

Just run the above example: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ff131d2f832ace9ffbdb67b15d116517)

### Actual Results
```
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): the trait bound `NodeIndex: From<Dummy>` is not satisfied
    --> src/main.rs:14:29
     |
14   |     graph.extend_with_edges(&[(d3, d1), (d3, d2), (d1, d4)]);
     |           ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<Dummy>` is not implemented for `NodeIndex`
     |           |
     |           required by a bound introduced by this call
     |
     = help: the trait `From<Ix>` is implemented for `NodeIndex<Ix>`
     = note: required for `Dummy` to implement `Into<NodeIndex>`
note: required by a bound in `Graph::<N, E, Ty, Ix>::extend_with_edges`
    --> /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/graph_impl/mod.rs:1332:51
     |
1332 |         <I::Item as IntoWeightedEdge<E>>::NodeId: Into<NodeIndex<Ix>>,
     |                                                   ^^^^^^^^^^^^^^^^^^^ required by this bound in `Graph::<N, E, Ty, Ix>::extend_with_edges`
```

### Expected Results

The [documentation for `extend_with_edges`](https://docs.rs/petgraph/latest/petgraph/graph/struct.Graph.html#method.extend_with_edges) says that the nodes are inserted automatically to match the edges. But above example doesn't compile due to trait bounds. However when you insert nodes beforehand the `extend_with_edges` compiles fine and correct: 
```rust
use petgraph::graph::Graph;
use petgraph::dot::{Dot, Config};

#[derive(Copy, Clone, Debug, Default)]
struct Dummy(usize);

fn main() {
    let d1 = Dummy(1);
    let d2 = Dummy(2);
    let d3 = Dummy(3);
    let d4 = Dummy(4);
    let mut graph = Graph::<Dummy, ()>::new();

    let n1 = graph.add_node(d1);
    let n2 = graph.add_node(d2);
    let n3 = graph.add_node(d3);
    let n4 = graph.add_node(d4);
    graph.extend_with_edges(&[(n3, n1), (n3, n2), (n1, n4)]);

    println!("{:?}", Dot::with_config(&graph, &[Config::EdgeNoLabel]));
}
```
I'm sorry if I misunderstood any trait bounds for the function, I tried to understand the core of `petgraph` by reading the source code, but I was lost during the process.

**Comment by insideoutclub** [comment]
In order for you Test Case to compile, you must implement the From<Dummy> trait for NodeIndex:

impl From<Dummy> for NodeIndex {
    fn from(x: Dummy) -> Self {
        NodeIndex::new(x.0)
    }
}

Here's a working playground link:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7dc8b31ef7af3901a4dd03f1645dc999

The documentation indicates this is its own roundabout way with the following Trait Bound:
<I::Item as IntoWeightedEdge<E>>::NodeId: Into<NodeIndex<Ix>>

While the trait bound may be hard to decipher, the compiler error message actually does a pretty good job of pointing out the correct solution:
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): the trait bound `NodeIndex: From<Dummy>` is not satisfied
    --> src/main.rs:14:29
     |
14   |     graph.extend_with_edges(&[(d3, d1), (d3, d2), (d1, d4)]);
     |           ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<Dummy>` is not implemented for `NodeIndex`

**Comment by m-spitfire** [comment]
Thank you so much for a detailed response! Although I figured it some time ago, I forgot to close the issue, but thanks again!!
