### ISSUE TITLE
Status of this crate

### ISSUE THREAD

**Issue by m-spitfire** [petgraph/petgraph#531]
First, thanks for the amazing library, I really appreciate your hard work!

What is the status of this crate from the maintainers' POV? The last issue that has been commented/closed by maintainers is #497, which was 6 months ago, and that issue had a PR sent with it. Other questions/reports in issues haven't been answered by then. I know that you're not obliged to answer everything that's going on in issues, but at least confirming bug reports and responding to feature requests can be helpful for the issue authors.

**Comment by m-spitfire** [comment]
cc: @ABorgna @XVilka @bluss

**Comment by ABorgna** [comment]
Hi. I think no one of the designated maintainers has been able to keep up with the crate lately. Unfortunately, this has been a [constant issue](https://github.com/petgraph/petgraph/pull/415#issuecomment-823391361).

Personally, I hope to start dedicating more time to petgraph soon(ish), but in the meantime we can always use more volunteers :) (cf. linked comment above).

**Comment by XVilka** [comment]
I do some odd reviews and arranging issues when I have time, I pinned the original issue that was looking for more maintainers.

**Comment by m-spitfire** [comment]
closing because of #551
