### ISSUE TITLE
Trait Rework: Unify `*Count` into `GraphLen`

### ISSUE THREAD

**Issue by indietyp** [petgraph/petgraph#554]
Unify `EdgeCount` and `NodeCount` into `GraphLen`, as it is unlikely that there are any cases where only one of them is implemented.

`Count` is also used in the contexts of iterators for getting the length while **consuming** the iterator.

```rust
pub struct Length {
	edges: usize,
	nodes: usize
}

impl Length {
	fn new() -> Self;
	fn edges() -> usize;
	fn nodes() -> usize;
}

pub trait GraphEdgeLen {
	fn edges_len(&self) -> usize;
}

pub trait GraphNodeLen {
	fn nodes_len(&self) -> usize;
}

pub trait GraphLen: GraphEdgeLen + GraphNodeLen {
	fn len(&self) -> Length {
		Length {edges: self.edges_len(), nodes: self.nodes_len()}
	}
}
```

**Comment by cojuer** [comment]
1. Aren't GraphEdgeLen/GraphNodeLen unnecessary in this case? User will have to choose between .nodes_len() and .len().nodes().
2. GraphLen seems less clear name than NodeCount/EdgeCount. Graph length is not commonly used term.
3. .len() usually returns usize for containers, seems a bit confusing to use it to return structure.

**Comment by indietyp** [comment]
Mhhh that is true, this is one of the proposals I am quite unsure about. On the one hand you are completely right with (3), then again `count()` is used for iterators and `len()` is used for containers, where `count()` is consuming, while `len()` is not.


Looking at other implementations, maybe we should use graph terminology here.

This means we would have:

* `GraphSize` (amount of edges, $`|E|`$)
* `GraphOrder` (amount of vertices/nodes, $`|V|`$)

This would avoid the pitfall of both `len()` and `count()`, but while accurate `GraphSize` as a name can be confusing for someone who is not familiar with graph theory.


```rust
pub trait GraphSize {
    /// Number of edges
    // name that is correct in regards to graph theory
	fn size(&self) -> usize;

	// inspiration has been taken from networkx, we could also just add an `edge_count` alias too
    // but I feel like in this case `number_of_edges` might be clearer and does not have the same connotation as count or len.
	fn number_of_edges(&self) -> usize {
		self.size()
	}
}

pub trait GraphOrder {
	/// Number of nodes
    // name that is correct in regards to graph theory
	fn order(&self) -> usize;

	fn number_of_nodes(&self) -> usize {
		self.order()
    }
}
```

What do you think @cojuer ?

**Comment by cojuer** [comment]
I like `GraphSize/GraphOrder` trait names, but I wouldn't use `size()/order()` functions (at least as the only option) to not confuse API users not familiar with graph theory. `number_of_edges/number_of_nodes` are fine, I would probably simplify those further (similar to `boost.graph`): num_nodes/num_edges.
