### ISSUE TITLE
How could I extract connected components by using a UnionFind?

### ISSUE THREAD

**Issue by bistace** [petgraph/petgraph#564]
Hello and thank you for developping petgraph!

I have a very large StableGraph and need to extract the connected components from this graph. I have seen in the codebase that there is a `connected_components` function that looks like this:
```rust
pub fn connected_components<G>(g: G) -> usize
where
    G: NodeCompactIndexable + IntoEdgeReferences,
{
    let mut vertex_sets = UnionFind::new(g.node_bound());
    for edge in g.edge_references() {
        let (a, b) = (edge.source(), edge.target());

        // union the two vertices of the edge
        vertex_sets.union(g.to_index(a), g.to_index(b));
    }
    let mut labels = vertex_sets.into_labeling();
    labels.sort_unstable();
    labels.dedup();
    labels.len()
}
```

I am a bit new to Rust (and graphs) and do not understand how (if possible) I could directly return the connected components instead of their numbers. Could you please point me in the right direction?

**Comment by indietyp** [comment]
Currently, `connected_components` only returns how many connected components there are, but you should be able to easily adapt it to figure out which the connected components are.

The main problem with adapting the code is that it relies on the fact that the graph must be `NodeCompactIndexable`, meaning there are no holes in your graph. This is not the case with `StableGraph`. You can remove nodes, which will create "holes"; therefore, it is no longer compact.

`vertex_sets.into_labeling()` returns a list where each index corresponds to a `NodeIndex`; the value is the component it is in. So you want to return that result and can then convert it to a data-structure of your liking.

I hope this helps!

**Comment by bistace** [comment]
Oh ok I see! I actually do not need StableGraph as I do not remove nodes. I will try to implement this by myself, thanks a lot for the pointers!

**Comment by bistace** [comment]
If someone else needs it, here's how I did it (keep in mind that I am a beginner in Rust so it is probably not optimized or idiomatic but it worked for me):
```rust
pub fn get_connected_components<'a>(
    g: &'a mut Graph<&str, (), Undirected, usize>,
) -> (usize, HashMap<usize, Vec<&'a str>>) {
    log::info!("Extracting connected components");

    // Each index of the Vec corresponds to a NodeIndex
    // The value at each index is a NodeId
    let component_indices = connected_components(g);
    let mut components: HashMap<usize, Vec<&str>> = HashMap::new();

    for (i, component_index) in component_indices.iter().enumerate() {
        let index: NodeIndex<usize> = node_index(i);
        components
            .entry(*component_index)
            .and_modify(|c| {
                c.push(g[index]);
            })
            .or_insert(vec![g[index]]);
    }

    (components.len(), components)
}

fn connected_components(g: &Graph<&str, (), Undirected, usize>) -> Vec<usize> {
    log::info!("Extracting labels");

    let mut vertex_sets = UnionFind::new(g.node_bound());
    for edge in g.edge_references() {
        let (a, b) = (edge.source(), edge.target());
        // union the two vertices of the edge
        vertex_sets.union(NodeIndexable::to_index(g, a), NodeIndexable::to_index(g, b));
    }

    vertex_sets.into_labeling()
}
```
