### ISSUE TITLE
find_negative_cycle / bellman ford algo

### ISSUE THREAD

**Issue by 0xfourzerofour** [petgraph/petgraph#565]
I was playing around with the algorithms provided by this library and specifically the bellman ford one.

I have a a graph with directed parallel edges however when I call the find_negative_cycle function it will return a vec of the Nodes however it does not let me know what edges are being traversed on each node as there couple be multiple going from a -> b due to the parallel design.

Is there a workaround for this or an addition to be able to retrieve the edge path along with the node list?

**Comment by ethever** [comment]
> Is there a workaround for this or an addition to be able to retrieve the edge path along with the node list?
how can you do that finally?
