### ISSUE TITLE
immediately_dominated_by function called on root of graph returns root itself

### ISSUE THREAD

**Issue by weigangd** [petgraph/petgraph#586]
Hello petgraph maintainers!

While using this amazing crate we stumbled upon 1 small bug. The documentation of the [immediately_dominated_by](https://docs.rs/petgraph/latest/petgraph/algo/dominators/struct.Dominators.html#method.immediately_dominated_by) states:

> Iterate over all nodes immediately dominated by the given node (not including the given node itself).

But when we call this function on a root of a graph the function returns the root itself. See the example.

If you have any questions please let me know.

Thank you 👋 

### Test Case

use petgraph::{algo::dominators, stable_graph::StableDiGraph};
fn main() {
    let mut graph: StableDiGraph<&str, ()> = StableDiGraph::new();
    let root = graph.add_node("ROOT");
    let a = graph.add_node("A");
    let b = graph.add_node("B");
    graph.extend_with_edges([(root, a), (root, b)]);
    let dominators = dominators::simple_fast(&graph, root);
    let dominated_by_root: Vec<_> = dominators
        .immediately_dominated_by(root)
        .map(|n| graph.node_weight(n).unwrap())
        .collect();
    println!("{:?}", dominated_by_root);
}

### Steps To Reproduce

 * Create a new binary project with petgraph as dependency
 * Paste the code in main.rs
 * let it run with cargo run

### Actual Results

["ROOT", "A", "B"]

### Expected Results

["A", "B"]

**Comment by ABorgna** [comment]
Fixed in #670
