### ISSUE TITLE
[Question] Generic algorithms that modify the graph

### ISSUE THREAD

**Issue by agubelu** [petgraph/petgraph#604]
Hi! Thanks for developing and maintaining Petgraph.

I've been using it for this year's Advent of Code, and one of the puzzles involves finding a minimum cut of the graph. To solve it, I implemented the [Stoer-Wagner algorithm](https://en.m.wikipedia.org/wiki/Stoer%E2%80%93Wagner_algorithm), and I thought it would be nice to give back to Petgraph by adding it to the `algo` module.

However, there are a couple of issues that I'd like to clarify before submitting a PR. They come mainly from the fact that the algorithm involves modifying and removing edges and nodes from the graph:

- I couldn't find a way to make it generic, since the common traits provide read-only methods, and `.remove_node()`, `.update_edge()`, etc aren't part of any traits.
- Since I need to remove nodes and edges without invalidating indexes and without modifying the user's graph, I decided to clone the graph into a `StableGraph`. To try to make it generic, I implemented `From<&Graph<...>> for StableGraph<...>` by cloning the graph, so I can ask the generic graph `G` to be `Into<StableUnGraph<G::NodeWeight, G::EdgeWeight, G::Ix>>`. However, `G::Ix` is never exposed so I can't turn a graph into a `StableGraph` generically. It also wouldn't support `GraphMap` because `StableGraph` has no `From` for it.

Are there any good solutions for these problems? If not, is it fine to just implement the algorithm for `StableGraph`  instead of generically?

Thanks again!

**Comment by indietyp** [comment]
Thanks! Yea the current version of 0.6.0 has some major limitations around it, which is why I am currently working on #567 a ground-up rework of petgraph to remove some of the limitations it is plagued by today.

The branch is currently very immature, many things are missing, but your best guess would be to target that version instead once it is in a more mature state, if you're up for it!

**Comment by agubelu** [comment]
Great, I'll keep an eye on it then. Thanks for the quick reply!
