### ISSUE TITLE
Please publish version 0.6.5

### ISSUE THREAD

**Issue by daniel-levin** [petgraph/petgraph#632]
### Summary

Since release 0.6.4, several features have been added, including:

- Rayon-ified APIs for `GraphMap`.
- Alternative hash function support in `GraphMap`.

### Motivation
These features are not available in a crate published on crates.io. These changes don't make breaking changes to petgraph's API, and it would be valuable for all users of the package to be able to use Rayon and alternative hash functions.

**Comment by daniel-levin** [comment]
@ABorgna is there any additional work I can do to make this easier?

**Comment by indietyp** [comment]
I'm sorry I haven't been as active lately. My personal life (including trying to balance university with work, free time, and OSS work) has been taking priority. I'll try to push out version 0.6.4 this weekend if I can. If no other maintainer has anything against it.

**Comment by ABorgna** [comment]
@indietyp  :+1: here

**Comment by daniel-levin** [comment]
@indietyp what can I do to help make this happen?

**Comment by indietyp** [comment]
Sorry, completely slipped my mind, will try to get to it this week!
