### ISSUE TITLE
read from shapefile/OSM and then calculate the shortest path

### ISSUE THREAD

**Issue by zhumingpassional** [petgraph/petgraph#633]
how to read from shapefile/OSM and then calculate the shortest path?
does it support shapefile/OSM?

**Comment by XVilka** [comment]
Hi, you need to parse the format yourself and form the petgraph data structures out of it. Then you could calculate the shortest path. Petgraph doesn't support these files out of the box nor it should. This format is domain-specific, and doesn't really belong in this crate. I recommend creating a new crate that uses and extends petgraph with that feature, and publish it, if necessary.
