### ISSUE TITLE
how to identify root nodes ?

### ISSUE THREAD

**Issue by JimFuller-RedHat** [petgraph/petgraph#660]
Apologies for the generic question !

Given any specific node I would like to efficiently 'walk up the tree' (from said node) to identify its root node ... bonus points if we can filter edge eg. only walking up edges of a particular type. 

Alternately I played with toposort (or breadth first traversal) to try and first identify all top level 'root' nodes and check connectedness that way.

More specifically:

1) how to identify a nodes top most ancestor node ?

2) how to identify all top level nodes in a graph (Assuming multi root is possible) ?

thx in advance ...

**Comment by milkcask** [comment]
I’m not sure what you're trying to do. While you can certainly encode a tree into one of the provided graph types, none of them inherently include a root node.

**Comment by JimFuller-RedHat** [comment]
I would define a 'root' node as one that has only incoming edges or depending on the graph 'direction', all outgoing direction ... never a mix. 

A toposort gets us most of the way there

```
import petgraph;
from petgraph.algo import topological_sort;

# Create a directed graph
graph = petgraph.DiGraph();

# Add nodes
graph.add_node("A");
graph.add_node("B");
graph.add_node("C");
graph.add_node("D");
graph.add_node("E");
graph.add_node("F");

# Add edges
graph.add_edge("A", "B");
graph.add_edge("A", "C");
graph.add_edge("B", "D");
graph.add_edge("B", "E");
graph.add_edge("C", "F");
graph.add_edge("E", "F");

# Find topmost 'root' nodes
topmost_nodes = [node for node in topological_sort(graph, reverse=True)
if graph.in_degree(node) == 0];

print(topmost_nodes);  # Output: should be 'A'

```
though we need a filter ... I think the best we can expect is  O(V + E) ...

**Comment by milkcask** [comment]
If the graph is truly a tree without any cycles, you can simply follow the edges from an arbitrary node until you reach a node with no incoming edges.

If the graph has cycles but still has a single root-like node, you can perform a partial depth-first search, only following the incoming edges. This method is more efficient than O(N + E) on average. For example:

```rust
use petgraph::{visit::{ NodeIndexable, VisitMap, Visitable}, Direction::Incoming};

fn main() {

    let tree = petgraph::graph::DiGraph::<u32, ()>::from_edges([
        (1, 2),
        (1, 3),
        (2, 4),
        (4, 5),
        (2, 5),
        (3, 6),
        (5, 6),
    ]);


    let mut discovered = tree.visit_map();
    let mut stack = Vec::new();

    stack.push(tree.from_index(6));

    while let Some(node) = stack.pop() {
        if discovered.visit(node) {
            for succ in tree.neighbors_directed(node, Incoming) {
                if !discovered.is_visited(&succ) {
                    stack.push(succ);
                }
            }
            if tree.neighbors_directed(node, Incoming).count() == 0 {
                println!("root node: {:?}", node);
            }
        }
    }

}
```

For a forest, you will have to visit every node. The traversal method doesn't really matter and the time complexity must be O(N+E).

**Comment by JimFuller-RedHat** [comment]
thx, thats similar to what I have though I matched on node values ... was not aware of Visitable approach (was using an vec for recording where we been (Assuming no other nodes had that value, which is not so correct). Going to close this issue as I got my answer.
