### ISSUE TITLE
How to transfer other types (such as usize) to NodeIndex, and other types to edge? 

### ISSUE THREAD

**Issue by zhumingpassional** [petgraph/petgraph#704]
How to transfer other types (such as usize) to NodeIndex, and other types to edge? 
let from: usize = 1; // NodeId : usize
let to: usize = 2;
let weight: usize = 3;
graph.add_node(from);
graph.add_node(to);
graph.add_edge(from, to, weight);// here the type of graph is DiGraph

It raises error: graph.add_node(from);
    |                        -------- ^^^^ expected `()`, found `usize`
    |                        arguments to this method are incorrect

Could you pls help me to solve this problem?

**Comment by starovoid** [comment]
Hi, you can try use node identifiers from `add_node` calls.

```rust
let from: usize = 1;
let to: usize = 2;
let weight: usize = 3;

// Try this:
let a = graph.add_node(from);
let b = graph.add_node(to);

graph.add_edge(a, b, weight);
```


To fully answer the question, it is necessary to know what type of `timeGraph` has.

**Comment by zhumingpassional** [comment]
@starovoid 
thanks for your valuable response.
what's the type of graph? I hope that it is directed graph. 
I tried your codes, if the type is DiGraph, it does not work.

thanks again for your quick response.

**Comment by starovoid** [comment]
> I tried the following code, which works:
> let from = 1;
> let to = 2;
> let mut graph: DiGraph<_, _> = DiGraph::new();
> let a = graph.add_node(from);
> let b = graph.add_node(to);
> graph.add_edge(a, b, 3);
> However, the edge of graph becomes (0, 1) with weight 3, not  (1, 2). why?
> ![image](https://github.com/user-attachments/assets/72f68387-a8a4-40e0-8c05-d41d89ede7fe)

This happens because `add_node` returns 'NodeIndex'. For `a` and `b`, the indexes are respectively `0` and `1`. The vertex weights are stored and accessed using the `node_weight` method. You can find the documentation [here](https://docs.rs/petgraph/latest/petgraph/graph/struct.Graph.html#method.add_node).

**Comment by starovoid** [comment]
> If I want to set the NodeIndex of node a as 3, and NodeIndex of node b as 5. How to implement it?

It is impossible to change the node index for the `Graph`, since this graph structure relies on a strict order of storing its elements.

**Comment by zhumingpassional** [comment]
thanks .
