### ISSUE TITLE
0.6.6 is a breaking release

### ISSUE THREAD

**Issue by LukeMathWalker** [petgraph/petgraph#712]
`petgraph@0.6.6` is a breaking release—`fixedbitset` is exposed through `petgraph`'s public API and it has been updated from `0.4.x` to `0.5.y`. For example: https://docs.rs/petgraph/latest/petgraph/adj/struct.List.html#method.is_adjacent 
And there are other spots where `fixedbitset` is directly used in `petrgraph`'s public API.

This caused breakage in downstream crates, e.g. `guppy`'s `0.17.x` no longer compiles if the latest `petgraph` is brought in as dependency. [Failed build triggered by this issue](https://github.com/LukeMathWalker/pavex/actions/runs/12558119886/job/35011774480).

Can you please yank `0.6.6`?
If you want to update to `fixedbitset@0.5.x`, you need to bump `petgraph`'s minor version to `0.7.x`.

**Comment by LukeMathWalker** [comment]
For others running into this issue: you can pin `petgraph` to `0.6.5` as a temporary workaround.

**Comment by starovoid** [comment]
@XVilka We need to fix this urgently. 
I suggest  yank `0.6.6` and
1. rolling back the changes to `fixedbitset` and quickly publish `0.6.7`
2. or release `0.7.0` as soon as possible, merging some other breaking changes, but moving #552 to `0.8.0`
